# Generated by Django 2.2.8 on 2021-10-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuotsong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuotsongquestion',
            name='questionSetID',
            field=models.IntegerField(default=1, verbose_name='Bộ câu hỏi'),
        ),
    ]
